Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,7 +4,7 @@ name: Run Tests
 on:
   release:
     types: [published]
-  workflow_dispatch:    # Добавлено для ручного запуска через интерфейс GitHub
+  workflow_dispatch:
 
 permissions:
   contents: write
@@ -32,11 +32,27 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt  # Установка зависимостей, включая тестовые
+        pip install -r requirements.txt
 
     - name: Run tests
       env:
         SELLER_ID: ${{ secrets.SELLER_ID }}
         API_KEY: ${{ secrets.API_KEY }}
       run: |
-        python -m unittest discover -s tests  # Запуск тестов в каталоге "tests"
+        python -m unittest discover -s tests
+
+    - name: Install build tools
+      run: |
+        python -m pip install build
+
+    - name: Build package
+      run: python -m build
+
+    - name: Verify Build Output
+      run: |
+        if [ -z "$(ls dist/*.whl 2>/dev/null)" ]; then
+          echo "Build failed: No .whl file found in dist directory."
+          exit 1
+        else
+          echo "Build successful: .whl file found."
+        fi
